### ISSUE TITLE
Package name change

### ISSUE THREAD

**Issue by vladimirnani** [iameugenejo/ngScrollTo#15]
I get this while installing from bower
`invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes`
Suggested name **angular-scroll-to**

**Comment by iameugenejo** [comment]
This may make other depended packages unable to fetch the newest release. Unless npm implements some sort of aliasing, renaming is not an option. Please refer to https://github.com/npm/npm/issues/2943
